AWSTemplateFormatVersion: '2010-09-09'
Description: 'GuardDuty Lambda function for SNS, Email and Google Chat notifications'

Parameters:
  SNSTopicArn:
    Type: String
    Description: ARN of the SNS topic to publish alerts
    Default: ''
  GoogleChatWebhook:
    Type: String
    Description: Google Chat webhook URL
    Default: ''
    NoEcho: true
  EnableSNS:
    Type: String
    Description: Enable SNS notifications
    Default: 'true'
    AllowedValues: ['true', 'false']
  EnableEmail:
    Type: String
    Description: Enable Email notifications
    Default: 'false'
    AllowedValues: ['true', 'false']
  EnableChat:
    Type: String
    Description: Enable Google Chat notifications
    Default: 'true'
    AllowedValues: ['true', 'false']

Resources:
  GuardDutyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-guardduty-lambda-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref SNSTopicArn
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-guardduty-lambda-role'
        - Key: 'Project'
          Value: 'MyProject'
        - Key: 'Environment'
          Value: 'prod'
        - Key: 'CreatedBy'
          Value: 'prashantgupta@cloudplatform.com'
        - Key: 'Owner'
          Value: 'prashantgupta@cloudplatform.com'

  GuardDutyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-guardduty-processor'
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      Role: !GetAtt GuardDutyLambdaRole.Arn
      Timeout: 60
      MemorySize: 128
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              return {
                  'statusCode': 200,
                  'body': json.dumps('Placeholder - Upload your deployment package')
              }
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref SNSTopicArn
          GOOGLE_CHAT_WEBHOOK: !Ref GoogleChatWebhook
          ENABLE_SNS: !Ref EnableSNS
          ENABLE_EMAIL: !Ref EnableEmail
          ENABLE_CHAT: !Ref EnableChat
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-guardduty-processor'
        - Key: 'Project'
          Value: 'MyProject'
        - Key: 'Environment'
          Value: 'prod'
        - Key: 'CreatedBy'
          Value: 'prashantgupta@cloudplatform.com'
        - Key: 'Owner'
          Value: 'prashantgupta@cloudplatform.com'

  GuardDutyEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-guardduty-rule'
      Description: 'EventBridge rule to trigger Lambda on GuardDuty findings'
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      State: ENABLED
      Targets:
        - Arn: !GetAtt GuardDutyLambdaFunction.Arn
          Id: GuardDutyLambdaTarget
      Tags:
        - Key: 'Name'
          Value: !Sub '${AWS::StackName}-guardduty-rule'
        - Key: 'Project'
          Value: 'MyProject'
        - Key: 'Environment'
          Value: 'prod'
        - Key: 'CreatedBy'
          Value: 'prashantgupta@cloudplatform.com'
        - Key: 'Owner'
          Value: 'prashantgupta@cloudplatform.com'

  GuardDutyLambdaFunctionRetryPolicy:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      FunctionName: !Ref GuardDutyLambdaFunction
      MaximumRetryAttempts: 0
      Qualifier: '$LATEST'
  
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GuardDutyLambdaFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt GuardDutyEventRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: 'ARN of the GuardDuty Lambda function'
    Value: !GetAtt GuardDutyLambdaFunction.Arn
  EventRuleArn:
    Description: 'ARN of the EventBridge rule'
    Value: !GetAtt GuardDutyEventRule.Arn